title: Sustainable Design
description: >- # this means to ignore newlines until "baseurl:"
  This is an awesome description of our class' website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  authors: