title: Sustainable Design
description: >- # this means to ignore newlines until "baseurl:"
  This is an awesome description of our class' website.
baseurl: "/publication" # the subpath of your site, e.g. /blog
url: "https://gd314-sgd.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

permalink: pretty

sass:
    sass_dir: assets/css

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_authors" # an empty string here means all files in the project
    values:
      layout: "author"
  -
    scope:
      path: "_entries" # an empty string here means all files in the project
    values:
      layout: "entry"

collections:
  authors:
    output: true
  entries:
    output: true